/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import ru.eltex.database.DefaultSchema;
import ru.eltex.database.tables.records.ManagersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Managers extends TableImpl<ManagersRecord> {

    private static final long serialVersionUID = -516907981;

    /**
     * The reference instance of <code>Managers</code>
     */
    public static final Managers MANAGERS = new Managers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManagersRecord> getRecordType() {
        return ManagersRecord.class;
    }

    /**
     * The column <code>Managers.id</code>.
     */
    public final TableField<ManagersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Managers.name</code>.
     */
    public final TableField<ManagersRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>Managers.phone</code>.
     */
    public final TableField<ManagersRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * Create a <code>Managers</code> table reference
     */
    public Managers() {
        this(DSL.name("Managers"), null);
    }

    /**
     * Create an aliased <code>Managers</code> table reference
     */
    public Managers(String alias) {
        this(DSL.name(alias), MANAGERS);
    }

    /**
     * Create an aliased <code>Managers</code> table reference
     */
    public Managers(Name alias) {
        this(alias, MANAGERS);
    }

    private Managers(Name alias, Table<ManagersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Managers(Name alias, Table<ManagersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ManagersRecord> getPrimaryKey() {
        return Internal.createUniqueKey(ru.eltex.database.tables.Managers.MANAGERS, "KEY_Managers_PRIMARY", ru.eltex.database.tables.Managers.MANAGERS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ManagersRecord>> getKeys() {
        return Arrays.<UniqueKey<ManagersRecord>>asList(
              Internal.createUniqueKey(ru.eltex.database.tables.Managers.MANAGERS, "KEY_Managers_PRIMARY", ru.eltex.database.tables.Managers.MANAGERS.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Managers as(String alias) {
        return new Managers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Managers as(Name alias) {
        return new Managers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Managers rename(String name) {
        return new Managers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Managers rename(Name name) {
        return new Managers(name, null);
    }
}
