/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.eltex.database.tables.DevAndLang;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevAndLangRecord extends UpdatableRecordImpl<DevAndLangRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -616675777;

    /**
     * Setter for <code>Dev_and_Lang.id_dev</code>.
     */
    public void setIdDev(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Dev_and_Lang.id_dev</code>.
     */
    public Integer getIdDev() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Dev_and_Lang.id_lang</code>.
     */
    public void setIdLang(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Dev_and_Lang.id_lang</code>.
     */
    public Integer getIdLang() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DevAndLang.DEV_AND_LANG.ID_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DevAndLang.DEV_AND_LANG.ID_LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdDev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdDev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevAndLangRecord value1(Integer value) {
        setIdDev(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevAndLangRecord value2(Integer value) {
        setIdLang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevAndLangRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevAndLangRecord
     */
    public DevAndLangRecord() {
        super(DevAndLang.DEV_AND_LANG);
    }

    /**
     * Create a detached, initialised DevAndLangRecord
     */
    public DevAndLangRecord(Integer idDev, Integer idLang) {
        super(DevAndLang.DEV_AND_LANG);

        set(0, idDev);
        set(1, idLang);
    }
}
