/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.eltex.database.tables.Langs;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangsRecord extends UpdatableRecordImpl<LangsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1784439235;

    /**
     * Setter for <code>Langs.id_lang</code>.
     */
    public void setIdLang(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Langs.id_lang</code>.
     */
    public Integer getIdLang() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Langs.lang</code>.
     */
    public void setLang(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Langs.lang</code>.
     */
    public String getLang() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Langs.LANGS.ID_LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Langs.LANGS.LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangsRecord value1(Integer value) {
        setIdLang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangsRecord value2(String value) {
        setLang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LangsRecord
     */
    public LangsRecord() {
        super(Langs.LANGS);
    }

    /**
     * Create a detached, initialised LangsRecord
     */
    public LangsRecord(Integer idLang, String lang) {
        super(Langs.LANGS);

        set(0, idLang);
        set(1, lang);
    }
}
