/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Langs implements Serializable {

    private static final long serialVersionUID = 136863143;

    private final Integer idLang;
    private final String  lang;

    public Langs(Langs value) {
        this.idLang = value.idLang;
        this.lang = value.lang;
    }

    public Langs(
        Integer idLang,
        String  lang
    ) {
        this.idLang = idLang;
        this.lang = lang;
    }

    public Integer getIdLang() {
        return this.idLang;
    }

    public String getLang() {
        return this.lang;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Langs (");

        sb.append(idLang);
        sb.append(", ").append(lang);

        sb.append(")");
        return sb.toString();
    }
}
