/*
 * This file is generated by jOOQ.
 */
package ru.eltex.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sale implements Serializable {

    private static final long serialVersionUID = 2064602006;

    private final Integer idSale;
    private final String  sale;
    private final Integer cost;

    public Sale(Sale value) {
        this.idSale = value.idSale;
        this.sale = value.sale;
        this.cost = value.cost;
    }

    public Sale(
        Integer idSale,
        String  sale,
        Integer cost
    ) {
        this.idSale = idSale;
        this.sale = sale;
        this.cost = cost;
    }

    public Integer getIdSale() {
        return this.idSale;
    }

    public String getSale() {
        return this.sale;
    }

    public Integer getCost() {
        return this.cost;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sale (");

        sb.append(idSale);
        sb.append(", ").append(sale);
        sb.append(", ").append(cost);

        sb.append(")");
        return sb.toString();
    }
}
